### ISSUE TITLE
how to make sure it babyagi-ui is updated 

### ISSUE THREAD

**Issue by youraveragenobody** [miurla/babyagi-ui#22]
hi there, excuse my question, completely new to this but love what you did with babyagi-ui!!! thank you very much, even with minimal starting knowledge I was able to get it to run.

my question is probably very mundane but could you advise on how to make sure one is running the most current version of baby-agi-ui?

**Comment by miurla** [comment]
Thank you for taking on the challenge!

Since we don't display whether it's the latest version on the screen, you'll need to check it using the git command in the terminal.

---

After moving to the project root, you can check it with the following command:

`git pull origin main`

With this command, the differences will be updated, or if it's already up-to-date, you'll see a message like the following, indicating that it's the latest version.


```
From github.com:miurla/babyagi-ui
 * branch            main       -> FETCH_HEAD
Already up to date.
```
