### ISSUE TITLE
AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by Maxximus69** [miurla/babyagi-ui#51]
Hey guys!

- I follow the Getting Started tutorial : https://github.com/miurla/babyagi-ui#-getting-started

- I don't use Pinecone index.

- I filled the OpenAI API key from the web interface. 

System Configuration :
- OS : Ventura 13.3.1 (a)
- Chip : Apple M1 Pro

BabyAGI configuration :
- Model : OpenAI gpt-4
- Agent : BabyCatAGI

**When I send a new objective, I got this error.**

<img width="1512" alt="Screenshot 2023-05-20 at 13 45 43" src="https://github.com/miurla/babyagi-ui/assets/40691025/36b9966f-6720-4f2e-9501-45b6cbdbbbd9">

Thank you for your good work @miurla

**Comment by miurla** [comment]
Thank you for trying it out.

Thank you for sharing the detailed error information. The error seems to be caused by a failure in the initial request to the OpenAI API. The occurrence of a 404 error suggests that there may be an issue with the account associated with the API key you are using.

Please check the following points:

- Do you have access to GPT-4?
- Or, have you not reached the usage limit?

ref: https://community.openai.com/t/using-api-with-the-model-gpt-4-gives-404/210744

**Comment by Maxximus69** [comment]
Ok I see : 
- Yes I'm using ChatGPT Plus.
- BabyAGI works with GPT 3.5.

I just subscribed for the GPT4 waiting list, thank you @miurla

**Comment by miurla** [comment]
Glad you were able to resolve this 👍 
Try it when you get access!

**Comment by Maxximus69** [comment]
Thank you, I will definitely! :)
